name: Release

on:
  workflow_dispatch:   # manual trigger from Actions tab
  pull_request:        # optional, builds changelog when PRs are opened/merged
  push:
    tags:
      - 'v*.*.*'   # runs when a version tag like v1.2.3 is pushed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build the changelog from merged PRs/issues
      - name: Build changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: .github/changelog-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

      # Publish GitHub Release with the changelog
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
